# Generated by Django 5.2.5 on 2026-07-14 00:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название системы')),
            ],
            options={
                'verbose_name': 'Система автомобиля',
                'verbose_name_plural': 'Системы автомобиля',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рекомендуемый пробег (км)')),
            ],
            options={
                'verbose_name': 'Пакет ТО',
                'verbose_name_plural': 'Пакеты ТО',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Двигатель')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска от')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска до')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'unique_together': {('make', 'model', 'engine')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Гос. номер')),
                ('current_mileage', models.PositiveIntegerField(default=0, verbose_name='Текущий пробег (км)')),
                ('first_registration_date', models.DateField(blank=True, null=True, verbose_name='Дата первой регистрации')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='technical_logbook.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандартный', max_length=100, verbose_name='Название цикла')),
                ('total_mileage', models.PositiveIntegerField(default=120000, verbose_name='Длина цикла (км)')),
                ('step_mileage', models.PositiveIntegerField(default=15000, verbose_name='Шаг между ТО (км)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='technical_logbook.carmodel', verbose_name='Для модели авто')),
            ],
            options={
                'verbose_name': 'Цикл ТО',
                'verbose_name_plural': 'Циклы ТО',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(default=datetime.date.today, verbose_name='Дата проведения')),
                ('mileage_at_service', models.PositiveIntegerField(verbose_name='Пробег на момент ТО (км)')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость работ (руб)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='technical_logbook.car', verbose_name='Автомобиль')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_logbook.maintenancepackage', verbose_name='Пакет ТО')),
            ],
            options={
                'verbose_name': 'Запись о ТО',
                'verbose_name_plural': 'Записи о ТО',
                'ordering': ['-date_performed'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название операции')),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Интервал пробега (км)')),
                ('interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Интервал времени (мес)')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Базовая стоимость работы (руб)')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='technical_logbook.carmodel', verbose_name='Для модели авто')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='technical_logbook.carsystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Регламентная операция',
                'verbose_name_plural': 'Регламентные операции',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecordTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_tasks', to='technical_logbook.maintenancerecord', verbose_name='Запись ТО')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technical_logbook.maintenancetask', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Выполненная операция',
                'verbose_name_plural': 'Выполненные операции',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(choices=[('oil', 'Масла и жидкости'), ('filter', 'Фильтры'), ('electrical', 'Электрика'), ('engine', 'Двигатель'), ('transmission', 'Трансмиссия'), ('suspension', 'Подвеска'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('expected_lifespan_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ожидаемый ресурс (км)')),
                ('expected_lifespan_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ожидаемый ресурс (мес)')),
                ('unit', models.CharField(choices=[('pcs', 'Штука'), ('liters', 'Литр'), ('kg', 'Килограмм'), ('set', 'Комплект')], default='pcs', max_length=10, verbose_name='Единица измерения')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу (руб)')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'unique_together': {('name', 'manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена за единицу (руб)')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('failed_prematurely', models.BooleanField(default=False, verbose_name='Преждевременный выход из строя')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technical_logbook.sparepart', verbose_name='Запчасть')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='technical_logbook.maintenancerecord', verbose_name='Запись ТО')),
            ],
            options={
                'verbose_name': 'Установленная запчасть',
                'verbose_name_plural': 'Установленные запчасти',
            },
        ),
        migrations.CreateModel(
            name='PackageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='Авто-распределение')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_logbook.maintenancepackage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_logbook.maintenancetask')),
            ],
            options={
                'unique_together': {('package', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TaskRequiredPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='Количество')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technical_logbook.carmodel', verbose_name='Модель авто')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_tasks', to='technical_logbook.sparepart', verbose_name='Запчасть')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_parts', to='technical_logbook.maintenancetask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Норматив расхода',
                'verbose_name_plural': 'Нормативы расхода',
                'unique_together': {('task', 'part', 'car_model')},
            },
        ),
    ]
